# Generated by Django 5.0.4 on 2024-07-03 07:17

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_remember_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.user_directory_avatars_path),
        ),
    ]
