# Generated by Django 5.0.4 on 2024-06-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='name',
            new_name='title',
        ),
    ]
