# Generated by Django 5.0.4 on 2024-06-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_projectfile_uploaded_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created_by',
            new_name='owner',
        ),
    ]
